services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=bcms'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    command:
      - --bind-address=0.0.0.0
      - --default-authentication-plugin=mysql_native_password
